- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
      # Make all the nodes aware of each other
      - name: update the hosts file
        template: src=templates/hosts.j2 dest=/etc/hosts

- hosts: master
  remote_user: vagrant
  sudo: yes
  tasks:

      # Install ansible
      - name: add ansible repo
        apt_repository: repo='ppa:ansible/ansible' update_cache=yes
      - name: install ansible
        apt: pkg=ansible state=present update_cache=yes
      - name: copy ansible playbooks
        copy: src=../ansible dest=/home/vagrant